//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geometry_api_cs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeometryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeometryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("geometry_api_cs.GeometryResources", typeof(GeometryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4001	0
        ///4002	0
        ///4003	0
        ///4004	0
        ///4005	0
        ///4006	0
        ///4007	0
        ///4008	0
        ///4009	0
        ///4010	0
        ///4011	0
        ///4012	0
        ///4013	0
        ///4014	0
        ///4015	0
        ///4016	0
        ///4018	0
        ///4019	0
        ///4020	0
        ///4021	0
        ///4022	0
        ///4023	0
        ///4024	0
        ///4025	0
        ///4027	0
        ///4028	0
        ///4029	0
        ///4031	0
        ///4032	0
        ///4033	0
        ///4034	0
        ///4035	0
        ///4036	0
        ///4042	0
        ///4044	0
        ///4045	0
        ///4046	0
        ///4047	0
        ///4052	0
        ///4053	0
        ///4054	0
        ///4075	0
        ///4081	0
        ///4120	0
        ///4121	0
        ///4122	0
        ///4123	0
        ///4124	0
        ///4125	0
        ///4126	0
        ///4127	0
        ///4128	0
        ///4129	0
        ///4130	0
        ///4131	0
        ///4132	0
        ///4133	0
        ///4134	0
        ///4135	0
        ///4136	0
        ///4137	0
        ///4138	0
        ///4139	0
        ///4140	0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gcs_id_to_tolerance {
            get {
                return ResourceManager.GetString("gcs_id_to_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	          1e-008
        ///1	    1.11111e-008
        ///2	    1.68845e-008
        ///3	    2.17661e-008
        ///4	    2.22508e-008
        ///5	    2.34848e-008
        ///6	    2.37811e-008
        ///7	    2.88455e-008
        ///8	     3.1456e-008
        ///9	    3.29779e-008
        ///10	    3.66789e-008
        ///11	    4.23597e-008
        ///12	    4.79463e-008
        ///13	    6.45223e-008
        ///14	    7.26274e-008
        ///15	    7.49945e-008
        ///16	    7.52506e-008
        ///17	    7.97991e-008
        ///18	    9.66202e-008
        ///19	    9.79918e-008
        ///20	    9.89735e-008
        ///21	    1.02314e-007
        ///22	    1.08146e-007
        ///23	    2.29734e-007
        ///24	    2.42985e-00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gcs_tolerances {
            get {
                return ResourceManager.GetString("gcs_tolerances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string intermediate_to_old_wkid {
            get {
                return ResourceManager.GetString("intermediate_to_old_wkid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2154	102110
        ///2195	102200
        ///2204	32036
        ///2205	26979
        ///2225	102641
        ///2226	102642
        ///2227	102643
        ///2228	102644
        ///2229	102645
        ///2230	102646
        ///2231	102653
        ///2232	102654
        ///2233	102655
        ///2234	102656
        ///2235	102657
        ///2236	102658
        ///2237	102659
        ///2238	102660
        ///2239	102666
        ///2240	102667
        ///2241	102668
        ///2242	102669
        ///2243	102670
        ///2246	102679
        ///2247	102680
        ///2248	102685
        ///2249	102686
        ///2250	102687
        ///2254	102694
        ///2255	102695
        ///2257	102712
        ///2258	102713
        ///2259	102714
        ///2260	102715
        ///2261	102716
        ///2262	102717
        ///2263	102718
        ///2264	102719
        ///2267	102724
        ///2268	10 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string new_to_old_wkid {
            get {
                return ResourceManager.GetString("new_to_old_wkid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000	3
        ///2001	3
        ///2002	3
        ///2003	3
        ///2004	3
        ///2005	3
        ///2006	3
        ///2007	3
        ///2008	3
        ///2009	3
        ///2010	3
        ///2011	3
        ///2012	3
        ///2013	3
        ///2014	3
        ///2015	3
        ///2016	3
        ///2017	3
        ///2018	3
        ///2019	3
        ///2020	3
        ///2021	3
        ///2022	3
        ///2023	3
        ///2024	3
        ///2025	3
        ///2026	3
        ///2027	3
        ///2028	3
        ///2029	3
        ///2030	3
        ///2031	3
        ///2032	3
        ///2033	3
        ///2034	3
        ///2035	3
        ///2036	3
        ///2037	3
        ///2038	3
        ///2039	3
        ///2040	3
        ///2041	3
        ///2042	3
        ///2043	3
        ///2044	3
        ///2045	3
        ///2056	3
        ///2057	3
        ///2058	3
        ///2059	3
        ///2060	3
        ///2061	3
        ///2062	3
        ///2063	3
        ///2064	3
        ///2065	3
        ///2066	6
        ///2067	3
        ///2068	3
        ///2069	3
        ///2070	3
        ///2071	3
        ///2072	3
        ///2073	3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pcs_id_to_tolerance {
            get {
                return ResourceManager.GetString("pcs_id_to_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	    6.66667e-009
        ///1	          2e-008
        ///2	    4.97098e-005
        ///3	           0.001
        ///4	      0.00109362
        ///5	      0.00328087
        ///6	      0.00497101
        ///.
        /// </summary>
        public static string pcs_tolerances {
            get {
                return ResourceManager.GetString("pcs_tolerances", resourceCulture);
            }
        }
    }
}
