/*
Copyright 2017 Echo Park Labs

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

For additional information, contact:

email: info@echoparklabs.io
*/
using NUnit.Framework;

namespace com.epl.geometry
{
	public class TestWktParser : NUnit.Framework.TestFixtureAttribute
	{
		[NUnit.Framework.Test]
		public virtual void TestGeometryCollection()
		{
			string s = "   geometrycollection    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.geometrycollection);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
			s = "   geometrycollection zm (  geometrycollection zm ( POINT ZM ( 5.  +1.e+0004 13 17) ), LineString  zm  emPty, MULTIpolyGON zM (((1 1 1 1))) ) ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.geometrycollection);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.geometrycollection);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.point);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.linestring);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multipolygon);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestMultiPolygon()
		{
			string s = "   MultIPolYgOn    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multipolygon);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  MULTIpolyGON zM ( empty , (  empty, ( 5.  +1.e+0004  13 17, -.1e07  .006 13 17 ) , empty  , (4  003. 13 17, 02E-3 .3e2 13 17)  ) , empty, ( ( 5.  +1.e+0004  13 17, -.1e07  .006  13 17) , (4  003. 13 17 , 02E-3 .3e2 13 17)  ) )   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multipolygon);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			// Start first polygon
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			// End of First polygon
			// Start Second Polygon
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestMultiLineString()
		{
			string s = "   MultiLineString    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multilinestring);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  MultiLineString Z (  empty, ( 5.  +1.e+0004  13, -.1e07  .006 13 ) , empty  , (4  003. 13 , 02E-3 .3e2 13 ) , empty, ( 5.  +1.e+0004  13 , -.1e07  .006  13) , (4  003. 13 , 02E-3 .3e2 13 )  )   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multilinestring);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_z);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestMultiPoint()
		{
			string s = "   MultipoInt    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multipoint);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  Multipoint Z (  empty, ( 5.  +1.e+0004  13 ), (-.1e07  .006 13 ) , empty  , (4  003. 13 ), (02E-3 .3e2 13 )  )   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			// bug here
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.multipoint);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_z);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestPolygon()
		{
			string s = "   Polygon    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.polygon);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  polyGON M (  empty, ( 5.  +1.e+0004  13, -.1e07  .006 13 ) , empty  , (4  003. 13 , 02E-3 .3e2 13 ) , empty, ( 5.  +1.e+0004  13 , -.1e07  .006  13) , (4  003. 13 , 02E-3 .3e2 13 )  )   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.polygon);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_m);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 4.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 3.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 2.0e-3);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.3e2);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestLineString()
		{
			string s = "   LineString    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.linestring);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  LineString ( 5.  +1.e+0004 , -.1e07  .006 )   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.linestring);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == -0.1e7);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 0.006);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
		}

		[NUnit.Framework.Test]
		public virtual void TestPoint()
		{
			string s = "   PoInT    emPty ";
			com.epl.geometry.WktParser wktParser = new com.epl.geometry.WktParser();
			wktParser.ResetParser(s);
			int currentToken;
			double value;
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.point);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.empty);
			s = "  POINT ZM ( 5.  +1.e+0004 13 17)   ";
			wktParser.ResetParser(s);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.point);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.attribute_zm);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.left_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.x_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 5.0);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.y_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 1.0e4);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.z_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 13);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.m_literal);
			value = wktParser.CurrentNumericLiteral();
			NUnit.Framework.Assert.IsTrue(value == 17);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.right_paren);
			currentToken = wktParser.NextToken();
			NUnit.Framework.Assert.IsTrue(currentToken == com.epl.geometry.WktParser.WktToken.not_available);
			s = "   PoInt ";
			wktParser.ResetParser(s);
			wktParser.NextToken();
		}
	}
}
